opendroid-spinner, openhdf-spinner, settings-autorestore - fixed bitbake errors
- in this commit: https://git.openembedded.org/bitbake/commit/?h=master-next&id=0c9302d950c6f37bfcc4256b41001d63f668bdf7
support of urls using globbing was dropped and bitbake throws following expansion error:

bb.data_smart.ExpansionError: Failure expanding variable do_fetch[file-checksums],
expression was ${@bb.fetch.get_checksum_file_list(d)}  ${@get_lic_checksum_file_list(d)} which triggered exception
ParameterError: URL: 'file://*' has invalid parameters. file:// urls using globbing are no longer supported.
Please place the files in a directory and reference that instead.

so let's fix such errors as suggested above