fix uses DATETIME variable , so the taskhash function changes
The buildsystem will complain accordingly:

ERROR: Taskhash mismatch f6fd355fd15dc99ccd7285ea5fc4f38e verses e0c654f7042b627d6138d535d40152a2