Revert "Update exteplayer3 und gstplayer"
This reverts commit 84ee081bd0731311c1118e7661c2216b078ac33f.

| /tmp/ccW8FW0w.o:(.data+0x50): undefined reference to `WriterVideoVP6'
| /tmp/ccW8FW0w.o:(.data+0x54): undefined reference to `WriterVideoVP8'
| /tmp/ccW8FW0w.o:(.data+0x58): undefined reference to `WriterVideoVP9'
| /tmp/ccW8FW0w.o:(.data+0x5c): undefined reference to `WriterVideoSPARK'
| collect2: error: ld returned 1 exit status