[Vu+] remove antiquated, unused and failing plugins
< 69705.351263> 08:13:10.8131   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/FirmwareUpgrade/plugin.py", line 590, in runDownloading
< 69705.355858> 08:13:10.8177   File "/usr/lib/enigma2/python/Plugins/SystemPlugins/FirmwareUpgrade/plugin.py", line 553, in doDownload
< 69705.357560> 08:13:10.8194 AttributeError: module 'six.moves.urllib' has no attribute 'URLopener'
< 69705.357949> 08:13:10.8198 [ePyObject] (CallObject(<bound method FUFilebrowser.runDownloading of <class 'Plugins.SystemPlugins.FirmwareUpgrade.plugin.FUFilebrowser'>>,()) failed)