busybox: avoid conflicts with mtd-utils
mtd-utils replaces include/mtd/* (e.g. mtd-user.h),
so while mtd-utils is being built (and old staging removed),
busybox fails to compile:
miscutils/flash_eraseall.c:21:26: fatal error: mtd/mtd-user.h: No such file or directory