update patch 0001-add-missing-defs.patch break build with some boxes
| src/common/dvb/dvb.h:22:14: error: nested redefinition of 'enum dmx_source'
|  typedef enum dmx_source {
|               ^~~~~~~~~~