Update gstreamer1.0-plugins-base_git.bb - remove no longer existing file COPYING.LIB from LIC_FILES_CHKSUM
ERROR: gstreamer1.0-plugins-base-1.14.1+gitAUTOINC+3ac37bbe67-r0 do_populate_lic: QA Issue: gstreamer1.0-plugins-base: LIC_FILES_CHKSUM points to an invalid file: /.../gstreamer1.0-plugins-base/1.14.1+gitAUTOINC+3ac37bbe67-r0/git/COPYING.LIB [license-checksum]