[vuplus] etherwol fix
ERROR: openatv-image-6.3-0 do_rootfs: Postinstall scriptlets of ['vuplus-ethwol'] have failed. If the intention is to defer them to first boot,
then please place them into pkg_postinst_ontarget_${PN} ().
Deferring to first boot via 'exit 1' is no longer supported.