[eglibc] ptrace: protect ptrace_peeksiginfo_args from redefintion
linux kernel commit 84c751bd [ptrace: add ability to retrieve signals without removing from a queue (v4)]
added ptrace_peeksiginfo_args to the exported kernel user api.

This leads to build errors such as:

| In file included from /poky-master/build/tmp/work/i586-poky-linux/strace/4.8-r0/strace-4.8/process.c:66:0:
| /poky-master/build/tmp/sysroots/qemux86/usr/include/linux/ptrace.h:58:8: error: redefinition of 'struct ptrace_peeksiginfo_args'
|  struct ptrace_peeksiginfo_args {
|         ^
| In file included from /poky-master/build/tmp/work/i586-poky-linux/strace/4.8-r0/strace-4.8/defs.h:159:0,
|                  from /poky-master/build/tmp/work/i586-poky-linux/strace/4.8-r0/strace-4.8/process.c:37:
| /poky-master/build/tmp/sysroots/qemux86/usr/include/sys/ptrace.h:191:8: note: originally defined here
|  struct ptrace_peeksiginfo_args
|         ^
| make[2]: *** [process.o] Error 1

In files that include both the eglibc sys/ptrace.h and the linux kernel exported
one.

We can avoid this by making the eglibc variant only declare its structure if PTRACE_PEEKSIGINFO
has not been defined.